gym/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

import gym
from . import views

app_name = "gym"

urlpatterns = [
    path('', views.home, name='home'),
    path('corso_search', views.corso_search, name='corso-search'),
    path('corso_dettagli/<int:id>', views.corso_dettagli, name='corso-dettagli'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/cliente', views.ClienteSignUpView.as_view(), name='cliente-signup'),
    path('pt_page/', views.pt_page, name='pt-page'),
    path('accounts/signup/pt', views.PtSignUpView.as_view(), name='pt-signup'),
    path('logout/', views.logout, name='logout'),
    path('dettagli_utente/<int:id>/', views.utente_details, name='utente-details'),
    path('ricerca_pt/', views.ricerca_pt, name='ricerca-pt'),
    path('ricerca_cliente/', views.ricerca_cliente, name='ricerca-cliente'),
    path('aggiungi_corso/', views.aggiungi_corso, name='aggiungi-corso'),
    path('iscrizione_corso/<int:id>', views.iscrizione_corso, name='iscrizione-corso'),
    path('iscrizione_delete/<int:id>', views.iscrizione_delete, name='iscrizione-delete'),
    path('elimina_corso/<int:id>', views.elimina_corso, name='elimina-corso'),
    path('avvenuta_eliminazione_corso/', views.avvenuta_eliminazione_corso, name='avvenuta-eliminazione-corso'),
    path('salda_iscrizione/<int:id>', views.salda_iscrizione, name='salda-iscrizione'),
    path('iscrizione_prolunga_method/<int:id>', views.iscrizione_prolunga_method, name='iscrizione-prolunga-method'),
    path('permesso_negato/', views.permesso_negato, name='permesso-negato'),
    path('nuova_scheda/', views.nuova_scheda, name='nuova-scheda'),
    path('elimina_scheda/<int:id>', views.elimina_scheda, name='elimina-scheda'),
    path('dettagli_scheda/<int:id>', views.dettagli_scheda, name='dettagli-scheda'),
    path('cerca_schede/', views.cerca_schede, name='cerca-schede'),
    path('aggiungi_esercizi/<int:id>', views.aggiungi_esercizi, name='aggiungi-esercizi'),
    path('elimina_esericizio/<int:id>', views.elimina_esercizio, name='elimina-esercizio'),
    path('consulta_calendario/<int:id>/', login_required(views.CalendarView.as_view()), name='consulta-calendario'),
    path('prenotazione/<int:pt_id>', views.prenotazione, name='prenotazione'),
]

mygym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = "mygym"

urlpatterns = [
    path('', include('gym.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gym/forms.py
from django import forms
from django.forms import DateInput

from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.contrib.auth import get_user_model

#Definisco quale classe user utilizzare
User = get_user_model()

#Form ricerca di un corso
class CorsoForm(forms.Form):
    nome = forms.CharField(max_length=100, label='Nome corso', required=False, initial="")
    prezzo_max = forms.FloatField(label='Prezzo massimo', required=False, initial=10000)

#Form registrazione di un cliente
class ClienteSignUpForm(UserCreationForm):
    foto_profilo = forms.ImageField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_cliente = True
        user.foto_profilo = self.cleaned_data.get('foto_profilo') #Aggiungo la foto profilo
        user.save()
        Cliente.objects.create(user=user)
        return user

    #Gestisco l'unicità della email
    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("La mail selezionata è già esistente")
        return data

#Form registrazione personal trainer
class PtSignUpForm(UserCreationForm):
    foto_profilo = forms.ImageField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_pt = True
        user.foto_profilo = self.cleaned_data.get('foto_profilo')
        user.save()
        Pt.objects.create(user=user)
        return user

    #Gestisco unicità mail
    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("La mail selezionata è già esistente")
        return data

#Form creazione utente generico
class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = '__all__'

    #Controllo che le password combacino
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

#Form aggiunta iscrizione
class IscrizioneAddForm(forms.ModelForm):
    class Meta:
        model = Iscrizione
        fields = ('mesi_durata',)

#Form aggiunta corso
class CorsoAddForm(forms.ModelForm):
    class Meta(forms.ModelForm):
        model = Corso
        exclude = ('iscritti_attuali', 'posti_rimanenti',)

    def save(self, commit=True):
        corso = super().save(commit=False)
        corso.foto = self.cleaned_data.get('foto')  #Foto corso
        corso.save()
        return corso

#Form per aggiornare immagine profilo sul proprio profilo utente
class UserUpdateForm(forms.Form):
    image = forms.ImageField(label='Aggiorna immagine profilo')

#Form per la ricerca di un utente generico
class UserSearchForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', )

#Form aggiunta di una nuova scheda
class SchedaAddForm(forms.ModelForm):
    class Meta:
        model = Scheda
        fields = ('nome', )

#Form ricerca di una scheda
class SchedeSearchForm(forms.Form):
    nome = forms.CharField(max_length=100, label='Nome scheda', required=False, initial="")
    autore = forms.CharField(max_length=100, label='Nome autore', required=False, initial="")

#Form aggiunta di un esercizio ad una scheda
class EsercizioAddForm(forms.ModelForm):
    class Meta:
        model = Esercizio
        fields = ('nome_esercizio', 'ripetizioni', 'serie', 'recupero', )

#Form di aggiunta di una prenotazione sul calendario di un pt
class PrenotazioneAddForm(forms.ModelForm):
    class Meta:
        model = Prenotazione
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'date': DateInput(),
            'start_time': DateInput(attrs={'type': 'time-local'}, format='%H:%M'),
            'end_time': DateInput(attrs={'type': 'time-local'}, format='%H:%M'),
        }
        labels = {
            "date": "Data (GG/MM/AAAA)",
            "start_time": "Ora di inizio (HH:MM)",
            "end_time": "Ora di fine (HH:MM)"
        }
        fields = ('date', 'start_time', 'end_time')

gym/views.py
import calendar

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django_tables2 import TemplateColumn, RequestConfig
from django.views import generic
from django.utils.safestring import mark_safe

from .forms import *
from .models import *
from .decorators import *
from .utils import *
from django.db.models import Q
from django.contrib.auth import login, user_logged_out
from django.shortcuts import redirect
from django.views.generic import CreateView
import django_tables2 as tables
from datetime import datetime, timedelta, date

#Home page del sito
def home(request):
    corsi = Corso.objects.all()
    logged_user = request.user
    context = {'corsi': corsi, 'logged_user': logged_user}
    return render(request, 'gym/home.html', context)

#Funzione di ricerca dei corsi e renderizzazione del risultato di tale ricerca
def corso_search(request):
    if request.method == 'POST':
        form = CorsoForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['nome'] == '' and form.cleaned_data['prezzo_max'] == 0.0: #Campi ricerca vuoti
                corsi = Corso.objects.all()
            else:
                corsi = Corso.objects.filter(Q(nome__icontains=form.cleaned_data['nome']) & Q(prezzo__lte=form.cleaned_data['prezzo_max'])) #Filtro ricerca
    else:
        form = CorsoForm
        corsi = Corso.objects.all()
    logged_user = request.user
    context = {'form': form, 'corsi': corsi, 'logged_user': logged_user}
    return render(request, 'gym/corso_search.html', context)

#Funzione di visualizzazione della pagina di dettagli di un corso
def corso_dettagli(request, id):
    corso = Corso.objects.get(id=id)
    try:
        iscrizione = Iscrizione.objects.get(cliente=request.user, corso=corso)
    except Iscrizione.DoesNotExist:
        iscrizione = None
    logged_user = request.user
    context = {'corso': corso, 'logged_user': logged_user, 'iscrizione': iscrizione}
    return render(request, 'gym/corso_dettagli.html', context)

#Pagina registrazione cliente
class ClienteSignUpView(CreateView):
    model = User
    form_class = ClienteSignUpForm
    template_name = 'gym/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'cliente'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('gym:home')

#Pagina registrazione pt
class PtSignUpView(CreateView):
    model = Pt
    form_class = PtSignUpForm
    template_name = 'gym/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'pt'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('gym:home')


@login_required
def logout(request):
    user = getattr(request, 'user', None)
    user = None
    user_logged_out.send(sender=User.__class__, request=request, user=User)
    request.session.flush()
    if hasattr(request, 'user'):
        request.user = AnonymousUser()
    return redirect('gym:home')


def pt_page(request):
    logged_user = request.user
    context = {'logged_user': logged_user}
    return render(request, 'gym/pt_page.html', context)

#Login condiviso da tutti gli utenti
def user_login(request):
    return redirect('gym:login')

#Pagina dettagli condivisa da tutti gli utenti
@login_required()
def utente_details(request, id):
    user = User.objects.get(id=id)
    corsi = Corso.objects.all()
    iscrizioni = Iscrizione.objects.filter(cliente_id=user.id)
    schede = Scheda.objects.filter(autore=user)
    if request.method == 'POST':                            #Update foto profilo
        form = UserUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            user.foto_profilo = form.cleaned_data['image']
            user.save()
            return redirect('gym:utente-details', id=id)
    else:
        form = UserUpdateForm()
    logged_user = request.user
    context = {'user': user, 'iscrizioni': iscrizioni, 'corsi': corsi, 'logged_user': logged_user, 'form': form, 'schede': schede}
    return render(request, 'gym/utente_dettagli.html', context)

#Tabella do visualizzazione dei risultati di ricerca su utenti
class ResultsTable(tables.Table):
    class Meta:
        model = User
        template_name = "django_tables2/bootstrap4.html"
        fields = ("first_name", "last_name", "email")
        attrs = {"class": "table table-striped table-bordered sortable",
                 "data-toggle": "table"
                 }

    detail = TemplateColumn(exclude_from_export=False, template_name='gym/button_details.html', orderable=False,
                            verbose_name='')

#Pagina ricerca pt che implementa la tabella ResultsTable
@login_required()
def ricerca_pt(request):
    pts = User.objects.filter(is_pt=True)
    table = ResultsTable(pts)
    RequestConfig(request, paginate={"per_page": 10}).configure(table) #Paginazione
    if request.method == 'POST':
        form = UserSearchForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['first_name'] == form.cleaned_data['last_name'] == form.cleaned_data['email'] == '': #Campi di ricerca vuoti
                pts = pts
            else:
                pts = pts.filter(Q(first_name__icontains=form.cleaned_data['first_name']) & Q(
                    last_name__icontains=form.cleaned_data['last_name']) & Q(
                    email__icontains=form.cleaned_data['email'])) #Filtro sui risultati
                table = ResultsTable(pts)
    else:
        form = UserSearchForm
    logged_user = request.user
    context = {'pts': pts, 'logged_user': logged_user, 'table': table, 'form': form}
    return render(request, 'gym/ricerca_pt.html', context)

#Pagina ricerca cliente
@login_required()
@portinaio_required()
def ricerca_cliente(request):
    clienti = User.objects.filter(is_cliente=True)
    table = ResultsTable(clienti)
    RequestConfig(request, paginate={"per_page": 10}).configure(table)
    if request.method == 'POST':
        form = UserSearchForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['first_name'] == form.cleaned_data['last_name'] == form.cleaned_data['email'] == '': #Campi ricerca vuoti
                clienti = clienti
            else:
                clienti = clienti.filter(Q(first_name__icontains=form.cleaned_data['first_name']) & Q(
                    last_name__icontains=form.cleaned_data['last_name']) & Q(email__icontains=form.cleaned_data['email'])) #Filtro ricerca
                table = ResultsTable(clienti)
    else:
        form = UserSearchForm
    logged_user = request.user
    context = {'clienti': clienti, 'logged_user': logged_user, 'table': table, 'form': form}
    return render(request, 'gym/ricerca_cliente.html', context)

#Funzione di aggiunta di un nuovo corso
@login_required()
@portinaio_required()
def aggiungi_corso(request):
    if request.method == 'POST':
        form = CorsoAddForm(request.POST, request.FILES)
        if form.is_valid():
            corso = form.save(commit=False)
            corso.save()
            return redirect('gym:corso-dettagli', id=corso.id)
    else:
        form = CorsoAddForm()
    logged_user = request.user
    context = {'logged_user': logged_user, 'form': form}
    return render(request, 'gym/aggiungi_corso.html', context)

#Funzione di iscrizione da parte di un cliente ad un corso
@login_required()
@cliente_required()
def iscrizione_corso(request, id):
    corso = Corso.objects.get(id=id)
    if request.method == 'POST':
        if corso.posti_rimanenti > 0:
            form = IscrizioneAddForm(request.POST)
            if form.is_valid():
                iscrizione = form.save(commit=False)
                iscrizione.corso_id = corso.id
                iscrizione.cliente_id = request.user.id
                iscrizione.costo_complessivo = iscrizione.mesi_durata * corso.prezzo
                iscrizione.data_iscrizione = datetime.now()
                iscrizione.data_scadenza = datetime.now() + (iscrizione.mesi_durata*timedelta(days=30))
                iscrizione.save()
                corso.iscritti_attuali += 1 #Iscritti rimanenti si aggiorna da solo
                corso.save()
                return redirect('gym:utente-details', id=iscrizione.cliente_id)
        else:
            redirect('gym:iscrizione-corso', id=id)
    else:
        form = IscrizioneAddForm
    logged_user = request.user
    context = {'logged_user': logged_user, 'form': form, 'corso': corso}
    return render(request, 'gym/iscrizione_corso.html', context)

#Cancellazione di una iscrizione
@login_required()
def iscrizione_delete(request, id):
    iscrizione = Iscrizione.objects.get(id=id)
    user = User.objects.get(id=iscrizione.cliente.id)
    corso = Corso.objects.get(id=iscrizione.corso.id)
    corso.iscritti_attuali -= 1 #Iscritti rimanenti si aggiorna da solo
    corso.save()
    iscrizione.delete()
    return redirect('gym:utente-details', user.id)

#Funzione di eliminazione di un corso
@login_required()
@portinaio_required()
def elimina_corso(request, id):
    corso = Corso.objects.get(id=id)
    corso.delete()
    return redirect('gym:avvenuta-eliminazione-corso')

#Portinaio usa questa funzione per saldare il debito di una singola iscrizione dell'utente
@login_required()
@portinaio_required()
def salda_iscrizione(request, id):
    iscrizione = Iscrizione.objects.get(id=id)
    cliente = User.objects.get(id=iscrizione.cliente.id)
    iscrizione.pagato = True
    iscrizione.costo_complessivo = 0
    iscrizione.save()
    return redirect('gym:utente-details', cliente.id)

gym/templates/gym/aggiungi_corso.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Aggiungi corso{% endblock %}

{% block content %}
    <!-- Template per l'aggiunta di un corso tramite form -->
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy}}
            <button type="submit" class="btn btn-primary mb-1">Aggiungi corso</button>
        </form>

    </div>

{% endblock %}

gym/templates/gym/aggiungi_esercizi.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Aggiungi esercizi alla scheda{% endblock %}

{% block content %}
    <!-- Template per l'aggiunta di un esercizio tramite modal ad una scheda di allenamento -->
    <div class="container">
        <p><strong>Scheda </strong>{{ scheda.nome }}</p>
        <p><strong>Autore </strong>{{ scheda.autore }}</p>
        <!-- Pulsante attivazione modal -->
        <button type="button" class="btn btn-info btn-sm mb-2" data-toggle="modal" data-target="#myModal{{ scheda.id }}">Aggiungi esercizio</button>
        <!-- Modal -->
        <div class="modal fade" id="myModal{{ scheda.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-full-height modal-bottom modal-notify" role="document">
                <div class="modal-content">
                      <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Aggiungi esercizio</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                      </div>
                    <!-- Inserimento dati -->
                    <form method="POST">
                      <div class="modal-body">
                        {% csrf_token %}
                        {{ form|crispy }}
                      </div>
                      <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                          <input type="submit" class="btn btn-info" value="Aggiungi">
                      </div>
                    </form>
                </div>
          </div>
        </div>
        <!-- Elenco esercizi in forma tabellare -->
        <table class="table table-striped table-bordered table-sm" data-toggle="table">
            <thead>
                <tr>
                    <th scope="col" data-sortable="true">Esercizio</th>
                    <th>Ripetizioni</th>
                    <th>Serie</th>
                    <th>Recupero</th>
                    <th style="width: 4%"></th>
                </tr>
            </thead>
            <tbody>
                {% for esercizio in esercizi %}
                    <tr>
                        <td scope="row" >{{ esercizio.nome_esercizio }}</td>
                        <td scope="row" >{{ esercizio.ripetizioni }}</td>
                        <td scope="row" >{{ esercizio.serie }}</td>
                        <td scope="row" >{{ esercizio.recupero }} sec</td>
                        <td>    <!-- Possibilità di rimuovere un esercizio -->
                            <a class="btn btn-danger btn-sm" href="{% url 'gym:elimina-esercizio' esercizio.id %}">Cancella</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

gym/templates/gym/avvenuta_eliminazione_corso.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Corso cancellato{% endblock %}

{% block content %}
    <!-- Template che indica la buona cancellazione di un corso -->
    <div style="width: 100%; height: 40vh; background: url('/static/images/clouds.jpg') no-repeat center; background-size: cover;">
        <h1 style="color: white; text-align:center; padding-top: 14vh">Corso cancellato con successo</h1>
    </div>
    <div class="container mt-2">

        <center>
            <a href="{% url 'gym:corso-search' %}" class="btn btn-primary">Torna alla ricerca dei corsi</a>
        </center>

    </div>

{% endblock %}

gym/templates/gym/button_details.html
<a class="btn btn-info btn-sm" href="{% url 'gym:utente-details' record.id %}">Vai al profilo</a>

<!-- Bottone usato in una ResultsTable che indica su quale profilo andare  -->

gym/templates/gym/cerca_schede.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load django_tables2 %}
{% block title %}Ricerca schede{% endblock %}

{% block content %}

    <div class="container">
        <!-- Template di ricerca di una scheda di allenamento -->
        <h3>Ricerca una scheda</h3>
        <form  method="post">
            {% csrf_token %}
            <div class="container">
                <div class="form-group">
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Cerca">
                </div>
            </div>
        </form>

        {% render_table table %}

    </div>

{% endblock %}

gym/templates/gym/corso_dettagli.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dettagli corso{% endblock %}

{% block content %}
    <!-- Template che visualizza i dettagli di un corso -->
    <div style="width: 100%; height: 30vh; background: url('/static/images/{{ corso.foto }}') no-repeat center; background-size: cover;">
        <h2 style="color: white; text-align:center; padding-top: 12vh">{{ corso.nome }}</h2>
    </div>
    <div class="container">
        <a href="{% url 'gym:corso-search' %}" class="btn btn-primary" style="margin-bottom: 10px; margin-top:10px;">Vai alla ricerca corsi</a>
        {% if corso.posti_rimanenti > 0 %}
            <!-- Controllo se posso iscrivermi ad un corso, ed in caso visualizzo il bottone (devo essere cliente e devono esserci posti disponibili -->
            {% if logged_user.is_cliente or logged_user.is_anonymous %}
                {% if iscrizione == None %}
                    <a href="{% url 'gym:iscrizione-corso' corso.id %}" class="btn btn-primary">Iscriviti al corso</a>
                {% else %}
                    <span>Sei già prenotato per questo corso</span>
                {% endif %}
            {% endif %}
        {% endif %}

        {% if logged_user.is_portinaio %}
            <a href="{% url 'gym:elimina-corso' corso.id %}" class="btn btn-danger">Elimina corso</a>
        {% endif %}
    </div>

    <div class="container">
        <div class="card" style="text-align: center; /*height: 80vh;*/ background: rgba(0, 0, 0, 0.1)">
                <p><strong>Nome corso: </strong>{{ corso.nome }}</p>
                <p><strong>Costo corso: </strong>{{ corso.prezzo|floatformat:2 }}€</p>
                <p class="card-text"><strong>Posti rimanenti:</strong> {{ corso.posti_rimanenti }}</p>
                <p><strong>Sedute settimanali: </strong>{{ corso.sedute_settimanali }}</p>
                <p><strong>Descrizione: </strong></p>
                <p>{{ corso.descrizione }}</p>
        </div>

    </div>

{% endblock %}

gym/templates/gym/corso_search.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Ricerca corso{% endblock %}

{% block content %}

    <div class="container">
        <!-- Template di ricerca di un corso. Mostro anche i risutlati della ricerca -->
        <h3>Ricerca un corso</h3>
        <form  method="post">
            {% csrf_token %}
            <div class="container">
                <div class="form-group">
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Cerca">
                </div>
            </div>
        </form>

        <!-- Risultati (inizialmente tutti i corsi -->
        <div class="row">
            {% for corso in corsi %}
            <div class="card col-mg-3" style="margin-bottom: 10px; width: 24%; margin-right: 0.5%; margin-left: 0.5%">
                <img class="card-img-top" src="{{ corso.fotoURL }}" style="width: 100%; height: 100%">
                <div class="card-body">
                    <h6 class="card-title">{{ corso.nome }}</h6>
                    <hr>
                    <p class="card-text">{{ corso.descrizione }}</p>
                    <p class="card-text">{{ corso.prezzo|floatformat:2 }}€</p>
                    <p class="card-text">{{ corso.posti_rimanenti }} posti rimanenti</p>
                    <a href="{% url 'gym:corso-dettagli' corso.id %}" class="btn btn-outline-secondary add-btn">Dettagli del corso</a>
                    {% if logged_user.is_portinaio %}
                        <a href="{% url 'gym:elimina-corso' corso.id %}" class="btn btn-danger mt-1">Elimina corso</a>
                    {% endif %}
                </div>
            </div>

            {% endfor %}
        </div>

    </div>

{% endblock %}

gym/templates/gym/dettagli_scheda.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dettagli scheda{% endblock %}

{% block content %}

    <div class="container mt-1">
        <!-- Template che visualizza una scheda e relativi esercizi -->
        <a href="{% url 'gym:cerca-schede' %}" class="btn btn-primary">Torna alla ricerca delle schede</a>
        <p><strong>Scheda </strong>{{ scheda.nome }}</p>
        <p><strong>Autore </strong>{{ scheda.autore }}</p>

        <table class="table table-striped table-bordered table-sm" data-toggle="table">
            <thead>
                <tr>
                    <th scope="col" data-sortable="true">Esercizio</th>
                    <th>Ripetizioni</th>
                    <th>Serie</th>
                    <th>Recupero</th>
                </tr>
            </thead>
            <tbody>
                {% for esercizio in esercizi %}
                    <tr>
                        <td scope="row" >{{ esercizio.nome_esercizio }}</td>
                        <td scope="row" >{{ esercizio.ripetizioni }}</td>
                        <td scope="row" >{{ esercizio.serie }}</td>
                        <td scope="row" >{{ esercizio.recupero }} sec</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

gym/templates/gym/pt_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sei un PT?{% endblock %}

{% block content %}

    <!-- Pagina che da la possibilità ad un utente anonimo di iscriversi come pt -->
    <div style="width: 100%; height: 40vh; background: url('/static/images/personal.jpg') no-repeat center; background-size: cover;">
        <h1 style="color: white; text-align:center; padding-top: 14vh">Vuoi diventare uno dei nostri PT?</h1>
    </div>

    <div class="container mt-2">

        <h4>Vuoi diventare un personal trainer presso la nostra palestra?</h4>
        <p>Registrati come tale!</p>
        <a class="btn btn-primary" href="{% url 'gym:pt-signup' %}">Sono un PT</a>

    </div>

{% endblock %}