gym/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

import gym
from . import views

app_name = "gym"

urlpatterns = [
    path('', views.home, name='home'),
    path('corso_search', views.corso_search, name='corso-search'),
    path('corso_dettagli/<int:id>', views.corso_dettagli, name='corso-dettagli'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/cliente', views.ClienteSignUpView.as_view(), name='cliente-signup'),
    path('pt_page/', views.pt_page, name='pt-page'),
    path('accounts/signup/pt', views.PtSignUpView.as_view(), name='pt-signup'),
    path('logout/', views.logout, name='logout'),
    path('dettagli_utente/<int:id>/', views.utente_details, name='utente-details'),
    path('ricerca_pt/', views.ricerca_pt, name='ricerca-pt'),
    path('ricerca_cliente/', views.ricerca_cliente, name='ricerca-cliente'),
    path('aggiungi_corso/', views.aggiungi_corso, name='aggiungi-corso'),
    path('iscrizione_corso/<int:id>', views.iscrizione_corso, name='iscrizione-corso'),
    path('iscrizione_delete/<int:id>', views.iscrizione_delete, name='iscrizione-delete'),
    path('elimina_corso/<int:id>', views.elimina_corso, name='elimina-corso'),
    path('avvenuta_eliminazione_corso/', views.avvenuta_eliminazione_corso, name='avvenuta-eliminazione-corso'),
    path('salda_iscrizione/<int:id>', views.salda_iscrizione, name='salda-iscrizione'),
    path('iscrizione_prolunga_method/<int:id>', views.iscrizione_prolunga_method, name='iscrizione-prolunga-method'),
    path('permesso_negato/', views.permesso_negato, name='permesso-negato'),
    path('nuova_scheda/', views.nuova_scheda, name='nuova-scheda'),
    path('elimina_scheda/<int:id>', views.elimina_scheda, name='elimina-scheda'),
    path('dettagli_scheda/<int:id>', views.dettagli_scheda, name='dettagli-scheda'),
    path('cerca_schede/', views.cerca_schede, name='cerca-schede'),
    path('aggiungi_esercizi/<int:id>', views.aggiungi_esercizi, name='aggiungi-esercizi'),
    path('elimina_esericizio/<int:id>', views.elimina_esercizio, name='elimina-esercizio'),
    path('consulta_calendario/<int:id>/', login_required(views.CalendarView.as_view()), name='consulta-calendario'),
    path('prenotazione/<int:pt_id>', views.prenotazione, name='prenotazione'),
]

mygym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = "mygym"

urlpatterns = [
    path('', include('gym.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'gym:home' %}">MyGym</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Componenti navbar -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gym:corso-search' %}">I nostri corsi</a>
                    </li>
                </ul>

                {% if user.is_authenticated %} <!-- Controllo se l'utente è loggato -->
                    <li class="nav-item navbar-nav">
                        <a class="nav-link" href="{% url 'gym:ricerca-pt' %}">Cerca PT</a>
                    </li>
                    <li class="nav-item navbar-nav">
                        <a class="nav-link" href="{% url 'gym:cerca-schede' %}">Cerca scheda</a>
                    </li>
                    {% if logged_user.is_portinaio %} <!-- In baso al tipo di utente mostro link diversi -->
                        <li class="nav-item navbar-nav">
                            <a class="nav-link" href="{% url 'gym:ricerca-cliente' %}">Cerca cliente</a>
                        </li>
                        <li class="nav-item navbar-nav">
                            <a class="nav-link" href="{% url 'gym:aggiungi-corso' %}">Aggiungi corso</a>
                        </li>
                    {% endif %}
                    {% if logged_user.is_pt %}
                        <li class="nav-item navbar-nav">
                            <a class="nav-link" href="{% url 'gym:nuova-scheda' %}">Aggiungi scheda</a>
                        </li>
                    {% endif %}
                    <!-- Dropdown comune a tutti gli utenti -->
                    <li class="nav-item dropdown my-lg-0 navbar-nav">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ logged_user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="margin-right: 0">
                            <a class="dropdown-item" href="{% url 'gym:utente-details' logged_user.id %}">Profilo</a>
                            <a class="dropdown-item" href="{% url 'gym:logout' %}">Log out</a>
                        </div>
                    </li>
                {% else %}
                    <div>   <!-- In caso non sia loggato do la possibilità di loggarsi o registrarsi come pt o cliente -->
                        <li class="nav-item navbar-nav">
                            <a class="nav-link" href="{% url 'gym:pt-page' %}">Sei un PT?</a>
                            <a href="{% url 'gym:login' %}" class="btn btn-warning nav-link" style="">Login</a>
                            <a href="{% url 'gym:cliente-signup' %}" class="btn btn-warning nav-link">Registrati</a>
                        </li>
                    </div>
                {% endif %}
            </div>
        </nav>

        <!-- Blocco contenuto -->
        <div class="mt-0 mb-1">
            {% block content %}{% endblock %}
        </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    </body>
</html>